### ISSUE TITLE
[EPIC] Release initial DCL-based resources using tpgtools

### ISSUE THREAD

**Issue by rileykarson** [hashicorp/terraform-provider-google#8206]
With the [Declarative Resource Client Library (DCL)](https://github.com/GoogleCloudPlatform/declarative-resource-client-library) becoming available, we can begin using the `tpgtools` generator to create Terraform resources. DCL+`tpgtools` collectively make up Magic Modules v2, the successor to the current "MMv1" generator at https://github.com/GoogleCloudPlatform/magic-modules. Working off of the already-declarative DCL, `tpgtools` is a much more lightweight code generator that we anticipate will have a much lower ongoing maintenance cost and lower latency before new resources and fields become available.

We've got a massive bank of resources in MMv1 already and we don't anticipate removing it entirely anytime soon. As a result we'll be running the `tpgtools` and MMv1 generators side-by-side in the https://github.com/GoogleCloudPlatform/magic-modules repo.

This issue tracks the introduction of `tpgtools` as a whole. Below are some of the sub-issues we've filed (so far!):

- [x] https://github.com/hashicorp/terraform-provider-google/issues/8198
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8199
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8200
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8201
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8202
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8203
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8204
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8069
- [ ] https://github.com/hashicorp/terraform-provider-google/issues/8205
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8207
- [x] https://github.com/hashicorp/terraform-provider-google/issues/8208

**Comment by rileykarson** [comment]
We did this one a while ago. We're up to 20+!
